"""
LowTemperaturePlasma_NoiseRobustness_Plots.py

Create MSE-vs-input-noise plots from the results generated by:
    LowTemperaturePlasma_NoiseRobustness.py

This script creates, for each architecture and each noise case:
    1. A full MSE-vs-noise plot
    2. A zoomed MSE-vs-noise plot

Each plot compares:
    - NN
    - NN + Projection

The y-axis uses the global output MSE:
    mse_all_mean ± mse_all_std

The uncertainty shown by the error bars is the standard deviation across the
Gaussian-noise seeds used in the robustness experiment.

Run from the project root:
    python LowTemperaturePlasma_NoiseRobustness_Plots.py
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter


# =============================================================================
# USER SETTINGS
# =============================================================================

# If this file is placed in the project root, this automatically points to the
# correct project folder.
PROJECT_ROOT = Path(__file__).resolve().parent

RESULTS_DIR = PROJECT_ROOT / "src" / "ltp_system" / "figures" / "Noise_Robustness"
SUMMARY_CSV = RESULTS_DIR / "noise_robustness_summary_results.csv"

OUTPUT_ROOT = RESULTS_DIR / "MSE_vs_Noise"

# Architectures to plot, in the order you want them generated.
# architecture_id must match the architecture_id column in the summary CSV.
ARCHITECTURES = [
    {"id": "30_30", "label": "[30, 30]"},
    {"id": "50_50", "label": "[50, 50]"},
    {"id": "30_30_30", "label": "[30, 30, 30]"},
]

NOISE_CASES = [
    "P_only",
    "I_only",
    "R_only",
    "P_I_R",
]

NOISE_CASE_LABELS = {
    "P_only": "P only",
    "I_only": "I only",
    "R_only": "R only",
    "P_I_R": "P + I + R",
}

MODEL_TYPES = [
    "NN",
    "NN_projection",
]

MODEL_LABELS = {
    "NN": "NN",
    "NN_projection": "NN + Projection",
}

# Main metric plotted on the y-axis.
# Other possible choices, if present in the CSV:
#   mse_O2X
#   mse_O2plus
#   mse_ne
METRIC = "mse_all"
METRIC_YLABEL = "Global output MSE (normalized output space)"

# Expected noise levels, in percent.
# The code will warn you if some of these are missing from the CSV.
EXPECTED_NOISE_LEVELS_PERCENT = [0.0, 0.5, 1.0, 2.0, 5.0, 10.0]
ONLY_PLOT_EXPECTED_NOISE_LEVELS = True

# y-axis scale.
# Recommended: "log"
# Alternative: "linear"
Y_SCALE = "log"

# Figure settings.
FIGSIZE = (7.2, 5.0)
DPI = 300
SAVE_FORMATS = ["png", "pdf"]

# Error bars.
SHOW_ERROR_BARS = True
ERROR_BAR_CAPSIZE = 4
ERROR_BAR_LINEWIDTH = 1.2
LINEWIDTH = 1.7
MARKERSIZE = 5

# Zoomed-plot settings.
MAKE_ZOOMED_PLOTS = True
ZOOM_XLIM = (0.0, 2.0)  # percent; default shows 0%, 0.5%, 1%, 2%
ZOOM_YLIM = None        # example: (1e-5, 1e-2). Leave None for automatic.
AUTO_ZOOM_Y_WITH_MARGIN = True
AUTO_ZOOM_MARGIN_FACTOR_LOG = 1.5
AUTO_ZOOM_MARGIN_FRACTION_LINEAR = 0.10

# Main plot limits.
# Leave as None for automatic limits.
MAIN_XLIM = None
MAIN_YLIM = None

# For log-scale plots, error bars cannot extend to zero or negative values.
# This clips the lower error bar only for visualization when std > mean.
LOG_ERRORBAR_MIN_FRACTION_OF_MEAN = 1e-6

# Output behavior.
OVERWRITE_EXISTING_PLOTS = True
PRINT_MISSING_LEVEL_WARNINGS = True


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def architecture_id_from_label(value: object) -> str:
    """Convert architecture labels like '[30, 30, 30]' into '30_30_30'."""
    numbers = re.findall(r"\d+", str(value))
    return "_".join(numbers)



def percent_tick_formatter(x: float, pos=None) -> str:
    """Format x-axis ticks as percentages."""
    if np.isclose(x, round(x)):
        return f"{int(round(x))}%"
    return f"{x:g}%"



def safe_float_array(values: Iterable) -> np.ndarray:
    """Convert a pandas Series/list to a finite-friendly float numpy array."""
    return pd.to_numeric(pd.Series(values), errors="coerce").to_numpy(dtype=float)



def rounded_set(values: Iterable[float], decimals: int = 6) -> set:
    return {round(float(v), decimals) for v in values if pd.notna(v)}



def ensure_required_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Validate and normalize the summary CSV columns."""
    required_base = [
        "architecture",
        "noise_case",
        "noise_std",
        "model_type",
    ]
    missing_base = [col for col in required_base if col not in df.columns]
    if missing_base:
        raise ValueError(
            "The summary CSV is missing required columns: "
            + ", ".join(missing_base)
        )

    if "architecture_id" not in df.columns:
        df = df.copy()
        df["architecture_id"] = df["architecture"].apply(architecture_id_from_label)

    if "noise_std_percent" not in df.columns:
        df = df.copy()
        df["noise_std_percent"] = 100.0 * pd.to_numeric(df["noise_std"], errors="coerce")

    mean_col = f"{METRIC}_mean"
    std_col = f"{METRIC}_std"
    missing_metric = [col for col in [mean_col, std_col] if col not in df.columns]
    if missing_metric:
        raise ValueError(
            "The summary CSV is missing required metric columns: "
            + ", ".join(missing_metric)
            + f"\nAvailable columns are:\n{list(df.columns)}"
        )

    return df



def load_summary_results(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Could not find summary results CSV:\n{path}\n\n"
            "Run LowTemperaturePlasma_NoiseRobustness.py first."
        )

    df = pd.read_csv(path)
    df = ensure_required_columns(df)
    return df



def get_architecture_folder_name(architecture_id: str) -> str:
    return f"arch_{architecture_id}"



def prepare_output_folder(architecture_id: str) -> Path:
    out_dir = OUTPUT_ROOT / get_architecture_folder_name(architecture_id)
    out_dir.mkdir(parents=True, exist_ok=True)
    return out_dir



def get_clean_baseline_row(
    df: pd.DataFrame,
    architecture_id: str,
    model_type: str,
) -> pd.DataFrame:
    """Return the clean 0% baseline row for one architecture/model type."""
    clean = df[
        (df["architecture_id"] == architecture_id)
        & (df["noise_case"] == "clean")
        & (df["model_type"] == model_type)
    ].copy()

    if clean.empty:
        return clean

    clean = clean.sort_values("noise_std_percent")
    clean = clean.iloc[[0]].copy()
    clean["noise_std"] = 0.0
    clean["noise_std_percent"] = 0.0

    # The clean baseline usually has only one row, so std columns may be NaN.
    # For plotting, this should be treated as zero uncertainty.
    for col in clean.columns:
        if col.endswith("_std"):
            clean[col] = clean[col].fillna(0.0)

    return clean



def get_noise_case_rows(
    df: pd.DataFrame,
    architecture_id: str,
    noise_case: str,
    model_type: str,
) -> pd.DataFrame:
    """Return non-clean rows for one architecture/noise case/model type."""
    rows = df[
        (df["architecture_id"] == architecture_id)
        & (df["noise_case"] == noise_case)
        & (df["model_type"] == model_type)
    ].copy()

    if rows.empty:
        return rows

    rows["noise_std_percent"] = pd.to_numeric(rows["noise_std_percent"], errors="coerce")
    rows = rows.sort_values("noise_std_percent")
    return rows



def get_plot_curve(
    df: pd.DataFrame,
    architecture_id: str,
    noise_case: str,
    model_type: str,
) -> pd.DataFrame:
    """
    Build the curve for a plot.

    The clean baseline is stored in the CSV as noise_case='clean'. This function
    copies that 0% point into every noise-case plot.
    """
    clean = get_clean_baseline_row(df, architecture_id, model_type)
    rows = get_noise_case_rows(df, architecture_id, noise_case, model_type)

    if clean.empty and rows.empty:
        return pd.DataFrame()

    curve = pd.concat([clean, rows], ignore_index=True)
    curve["noise_std_percent"] = pd.to_numeric(curve["noise_std_percent"], errors="coerce")
    curve = curve.dropna(subset=["noise_std_percent"])

    # Remove duplicate 0% points if the CSV already contains baseline points for
    # this specific noise case.
    curve["noise_std_percent_rounded"] = curve["noise_std_percent"].round(6)
    curve = curve.drop_duplicates(subset=["noise_std_percent_rounded"], keep="first")
    curve = curve.drop(columns=["noise_std_percent_rounded"])

    if ONLY_PLOT_EXPECTED_NOISE_LEVELS:
        expected = rounded_set(EXPECTED_NOISE_LEVELS_PERCENT)
        curve = curve[curve["noise_std_percent"].round(6).isin(expected)]

    curve = curve.sort_values("noise_std_percent")
    return curve



def warn_missing_noise_levels(
    curve: pd.DataFrame,
    architecture_label: str,
    noise_case: str,
    model_label: str,
) -> None:
    if not PRINT_MISSING_LEVEL_WARNINGS:
        return

    present = rounded_set(curve["noise_std_percent"].to_numpy())
    expected = rounded_set(EXPECTED_NOISE_LEVELS_PERCENT)
    missing = sorted(expected - present)

    if missing:
        print(
            "Warning: missing noise levels for "
            f"architecture {architecture_label}, "
            f"case {noise_case}, model {model_label}: "
            f"{missing} %"
        )



def extract_xyerr(curve: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    mean_col = f"{METRIC}_mean"
    std_col = f"{METRIC}_std"

    x = safe_float_array(curve["noise_std_percent"])
    y = safe_float_array(curve[mean_col])
    yerr = safe_float_array(curve[std_col])
    yerr = np.nan_to_num(yerr, nan=0.0, posinf=0.0, neginf=0.0)
    yerr = np.maximum(yerr, 0.0)

    finite_mask = np.isfinite(x) & np.isfinite(y) & np.isfinite(yerr)

    if Y_SCALE == "log":
        # Log-scale plots cannot display zero or negative y-values.
        finite_mask = finite_mask & (y > 0.0)

    return x[finite_mask], y[finite_mask], yerr[finite_mask]



def make_yerr_for_plot(y: np.ndarray, yerr: np.ndarray):
    """Create y-error values that are safe for linear or log plots."""
    if not SHOW_ERROR_BARS:
        return None

    if Y_SCALE != "log":
        return yerr

    lower_limit = y * LOG_ERRORBAR_MIN_FRACTION_OF_MEAN
    lower_error = np.minimum(yerr, np.maximum(y - lower_limit, 0.0))
    upper_error = yerr
    return np.vstack([lower_error, upper_error])



def collect_auto_ylim_data(
    curves_data: Sequence[Tuple[np.ndarray, np.ndarray, np.ndarray]],
    xlim: Optional[Tuple[float, float]],
) -> Tuple[np.ndarray, np.ndarray]:
    lows: List[float] = []
    highs: List[float] = []

    for x, y, yerr in curves_data:
        if len(x) == 0:
            continue

        mask = np.isfinite(x) & np.isfinite(y) & np.isfinite(yerr)
        if xlim is not None:
            mask = mask & (x >= xlim[0]) & (x <= xlim[1])

        x_sel = x[mask]
        y_sel = y[mask]
        yerr_sel = yerr[mask]

        if len(x_sel) == 0:
            continue

        low = y_sel - yerr_sel
        high = y_sel + yerr_sel

        if Y_SCALE == "log":
            positive_fallback = y_sel * LOG_ERRORBAR_MIN_FRACTION_OF_MEAN
            low = np.where(low > 0.0, low, positive_fallback)
            valid = (low > 0.0) & (high > 0.0) & np.isfinite(low) & np.isfinite(high)
            low = low[valid]
            high = high[valid]
        else:
            valid = np.isfinite(low) & np.isfinite(high)
            low = low[valid]
            high = high[valid]

        lows.extend(low.tolist())
        highs.extend(high.tolist())

    return np.asarray(lows, dtype=float), np.asarray(highs, dtype=float)



def automatic_ylim(
    curves_data: Sequence[Tuple[np.ndarray, np.ndarray, np.ndarray]],
    xlim: Optional[Tuple[float, float]],
) -> Optional[Tuple[float, float]]:
    lows, highs = collect_auto_ylim_data(curves_data, xlim)

    if len(lows) == 0 or len(highs) == 0:
        return None

    ymin = float(np.nanmin(lows))
    ymax = float(np.nanmax(highs))

    if not np.isfinite(ymin) or not np.isfinite(ymax):
        return None

    if ymin == ymax:
        if Y_SCALE == "log":
            return ymin / AUTO_ZOOM_MARGIN_FACTOR_LOG, ymax * AUTO_ZOOM_MARGIN_FACTOR_LOG
        delta = abs(ymin) * AUTO_ZOOM_MARGIN_FRACTION_LINEAR
        if delta == 0:
            delta = 1.0
        return ymin - delta, ymax + delta

    if Y_SCALE == "log":
        if ymin <= 0.0:
            return None
        return ymin / AUTO_ZOOM_MARGIN_FACTOR_LOG, ymax * AUTO_ZOOM_MARGIN_FACTOR_LOG

    margin = AUTO_ZOOM_MARGIN_FRACTION_LINEAR * (ymax - ymin)
    return ymin - margin, ymax + margin



def apply_axis_formatting(
    ax,
    architecture_label: str,
    noise_case: str,
    zoomed: bool,
    curves_data: Sequence[Tuple[np.ndarray, np.ndarray, np.ndarray]],
) -> None:
    noise_label = NOISE_CASE_LABELS.get(noise_case, noise_case)
    title_prefix = "Zoomed: " if zoomed else ""

    ax.set_title(f"{title_prefix}Architecture {architecture_label} — {noise_label} noise")
    ax.set_xlabel("Input noise standard deviation")
    ax.set_ylabel(METRIC_YLABEL)

    ax.xaxis.set_major_formatter(FuncFormatter(percent_tick_formatter))
    ax.set_xticks(EXPECTED_NOISE_LEVELS_PERCENT)

    if Y_SCALE in {"linear", "log"}:
        ax.set_yscale(Y_SCALE)
    else:
        raise ValueError("Y_SCALE must be either 'linear' or 'log'.")

    ax.grid(True, which="both", alpha=0.30)
    ax.legend()

    if zoomed:
        ax.set_xlim(ZOOM_XLIM)
        if ZOOM_YLIM is not None:
            ax.set_ylim(ZOOM_YLIM)
        elif AUTO_ZOOM_Y_WITH_MARGIN:
            ylim = automatic_ylim(curves_data, ZOOM_XLIM)
            if ylim is not None:
                ax.set_ylim(ylim)
    else:
        if MAIN_XLIM is not None:
            ax.set_xlim(MAIN_XLIM)
        if MAIN_YLIM is not None:
            ax.set_ylim(MAIN_YLIM)



def save_figure(fig, output_dir: Path, base_filename: str) -> List[Path]:
    saved_paths = []

    for fmt in SAVE_FORMATS:
        out_path = output_dir / f"{base_filename}.{fmt}"

        if out_path.exists() and not OVERWRITE_EXISTING_PLOTS:
            raise FileExistsError(
                f"File already exists and OVERWRITE_EXISTING_PLOTS=False:\n{out_path}"
            )

        if fmt.lower() == "png":
            fig.savefig(out_path, dpi=DPI, bbox_inches="tight")
        else:
            fig.savefig(out_path, bbox_inches="tight")

        saved_paths.append(out_path)

    return saved_paths



def plot_one_case(
    df: pd.DataFrame,
    architecture_id: str,
    architecture_label: str,
    noise_case: str,
    output_dir: Path,
    zoomed: bool = False,
) -> List[Path]:
    fig, ax = plt.subplots(figsize=FIGSIZE)
    curves_data: List[Tuple[np.ndarray, np.ndarray, np.ndarray]] = []
    plotted_anything = False

    for model_type in MODEL_TYPES:
        model_label = MODEL_LABELS.get(model_type, model_type)
        curve = get_plot_curve(df, architecture_id, noise_case, model_type)

        if curve.empty:
            print(
                f"Warning: no data for architecture {architecture_label}, "
                f"case {noise_case}, model {model_label}."
            )
            continue

        warn_missing_noise_levels(curve, architecture_label, noise_case, model_label)

        x, y, yerr = extract_xyerr(curve)
        if len(x) == 0:
            print(
                f"Warning: no finite positive {METRIC} values for architecture "
                f"{architecture_label}, case {noise_case}, model {model_label}."
            )
            continue

        curves_data.append((x, y, yerr))
        yerr_plot = make_yerr_for_plot(y, yerr)

        ax.errorbar(
            x,
            y,
            yerr=yerr_plot,
            marker="o",
            markersize=MARKERSIZE,
            linewidth=LINEWIDTH,
            elinewidth=ERROR_BAR_LINEWIDTH,
            capsize=ERROR_BAR_CAPSIZE if SHOW_ERROR_BARS else 0,
            label=model_label,
        )
        plotted_anything = True

    if not plotted_anything:
        plt.close(fig)
        return []

    apply_axis_formatting(
        ax,
        architecture_label=architecture_label,
        noise_case=noise_case,
        zoomed=zoomed,
        curves_data=curves_data,
    )

    zoom_suffix = "_zoom" if zoomed else ""
    base_filename = f"{METRIC}_vs_noise_{noise_case}_arch_{architecture_id}{zoom_suffix}"
    saved_paths = save_figure(fig, output_dir, base_filename)
    plt.close(fig)

    return saved_paths



def create_plots(df: pd.DataFrame) -> pd.DataFrame:
    created_records = []

    for architecture in ARCHITECTURES:
        architecture_id = architecture["id"]
        architecture_label = architecture["label"]
        output_dir = prepare_output_folder(architecture_id)

        arch_data = df[df["architecture_id"] == architecture_id]
        if arch_data.empty:
            print(f"Warning: architecture {architecture_label} not found in the summary CSV.")
            continue

        print("\n" + "=" * 80)
        print(f"Creating plots for architecture {architecture_label}")
        print(f"Output folder: {output_dir}")
        print("=" * 80)

        for noise_case in NOISE_CASES:
            print(f"  Plotting noise case: {noise_case}")

            saved_main = plot_one_case(
                df=df,
                architecture_id=architecture_id,
                architecture_label=architecture_label,
                noise_case=noise_case,
                output_dir=output_dir,
                zoomed=False,
            )

            for path in saved_main:
                created_records.append(
                    {
                        "architecture": architecture_label,
                        "architecture_id": architecture_id,
                        "noise_case": noise_case,
                        "metric": METRIC,
                        "plot_type": "main",
                        "file": str(path),
                    }
                )

            if MAKE_ZOOMED_PLOTS:
                saved_zoom = plot_one_case(
                    df=df,
                    architecture_id=architecture_id,
                    architecture_label=architecture_label,
                    noise_case=noise_case,
                    output_dir=output_dir,
                    zoomed=True,
                )

                for path in saved_zoom:
                    created_records.append(
                        {
                            "architecture": architecture_label,
                            "architecture_id": architecture_id,
                            "noise_case": noise_case,
                            "metric": METRIC,
                            "plot_type": "zoom",
                            "file": str(path),
                        }
                    )

    created_df = pd.DataFrame(created_records)
    return created_df



def main() -> None:
    print("\nCreating MSE-vs-noise robustness plots...")
    print(f"Reading summary CSV:\n  {SUMMARY_CSV}")

    df = load_summary_results(SUMMARY_CSV)
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    created_df = create_plots(df)

    if created_df.empty:
        print("\nNo plots were created. Check the warnings above.")
        return

    index_path = OUTPUT_ROOT / f"{METRIC}_created_plots_index.csv"
    created_df.to_csv(index_path, index=False)

    print("\nDone.")
    print(f"Created {len(created_df)} files.")
    print(f"Plot index saved to:\n  {index_path}")
    print(f"Main output folder:\n  {OUTPUT_ROOT}")


if __name__ == "__main__":
    main()
